### ISSUE TITLE
WeChat Backend Access for Customer Service

### ISSUE THREAD

**Issue by TedHopkins** [ProPurteam/Project-Purple#6]
Need to grant access to wechat backend for live Q&A to customer service to Eva and her team. They will provide support on Saturday and Sunday.

@GinaWuSams 

Gina please add Andrea and Claire to this group.

**Comment by GinaWuSams** [comment]
@andreapanpan @clairehu00 please help herem thank you!

**Comment by andreapanpan** [comment]
@aleck-wmt Can you please help grant access to the service account backend for Eva and her team by tmr? Thanks!

**Comment by aleck-wmt** [comment]
Sure, sent invitation already
